fix: fix BaseRecord.param(path) returning [null]
SoftwareBrothers/admin-bro pull request #635
Opened 2020-10-09 13:27 UTC by dziraf

This is a fix to: https://github.com/SoftwareBrothers/admin-bro/issues/634
However, I've no idea why `flat.get(...)` would return `[null]`.

2020-10-09 13:29 UTC, dziraf commented on src/backend/adapters/record/base-record.ts
> +    if (Array.isArray(paramValue) && paramValue.every(v => !v)) {
Unsure about `every` vs `some`. I don't know if it's possible to get more than one `null` in this issue

2020-10-11 04:20 UTC, wojtek-krysiak commented
@dziraf thanks for the update. I would make 2 changes:

1. move this to the flat.get since it should replace all the places where we flat/unflat properties
2. write unit test in get: https://github.com/SoftwareBrothers/admin-bro/blob/bb9de777d67e3425928a2b6a8825626c7f9bc4bd/src/utils/flat/get.spec.ts#L9-L9 covering this particular issue

2020-10-11 04:21 UTC, wojtek-krysiak requested changes
@dziraf thanks for the update. I would make 2 changes:

1. move this to the flat.get since it should replace all the places where we flat/unflat properties
2. write unit test in get: https://github.com/SoftwareBrothers/admin-bro/blob/bb9de777d67e3425928a2b6a8825626c7f9bc4bd/src/utils/flat/get.spec.ts#L9-L9 covering this particular issue

2020-10-11 10:16 UTC, wojtek-krysiak commented
@dziraf but wait - I think I fixed that 2 days ago here: https://github.com/SoftwareBrothers/admin-bro/commit/bb9de777d67e3425928a2b6a8825626c7f9bc4bd#diff-15b392d592d49fff9fe23078e53a9474R22

so if the value was null or 0 (before) it didn't return it directly but instead, it went further in the code eventually resolving to Array of nulls

2020-10-23 01:52 UTC, wojtek-krysiak commented
closing because it was already fixed

2020-10-23 01:52 UTC, closed without merging